@Library('Trator@main')

import com.tarator.jobs.JobParameters
import com.tarator.jobs.Agent
import com.tarator.jobs.parameters.ParametersBuildBase

def parameters = new ParametersBuildBase(this, env.JOB_BASE_NAME)
parameters.addGeneralBuildParams()

pipeline {
    agent {
        kubernetes {
            cloud Agent.K8S_TARATOR
            yaml Agent.getKubernetesAgentYaml()
        }
    }

    environment {
        PYTHON_ENV = "venv"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Set Up Python Environment') {
            steps {
                script {
                    if (!fileExists("${PYTHON_ENV}")) {
                        sh 'python3 -m venv venv'
                    }
                    sh '. venv/bin/activate'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '. venv/bin/activate && pip install --upgrade pip'
                sh '. venv/bin/activate && pip install -r app/requirements.txt'
            }
        }

        stage('Run Unit Tests') {
            when { expression { return params.RUN_UNIT_TESTS } }
            steps {
                sh '. venv/bin/activate && pytest app/test_app.py --junitxml=results.xml'
            }
            post {
                always {
                    junit 'results.xml'
                }
            }
        }

        stage('Code Coverage') {
            when { expression { return params.PUBLISH_COVERAGE } }
            steps {
                sh '. venv/bin/activate && coverage run -m pytest app/test_app.py'
                sh '. venv/bin/activate && coverage report'
                sh '. venv/bin/activate && coverage xml'
            }
            post {
                always {
                    publishCoverage adapters: [coberturaAdapter('coverage.xml')]
                }
            }
        }

        stage('Linting') {
            when { expression { return params.ENABLE_LINTING } }
            steps {
                sh '. venv/bin/activate && flake8 app/'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t sudoku:${params.DOCKER_IMAGE_TAG} ."
            }
        }

        stage('Deploy to Environment') {
            when { expression { return params.DEPLOY_ENVIRONMENT != 'none' } }
            steps {
                sh 'echo Deploying to ${params.DEPLOY_ENVIRONMENT} environment...'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}