@Library('Trator@main')

import com.tarator.jobs.triggers.TriggersBase

def triggers = new TriggersBase(this, env.JOB_BASE_NAME)
triggers.addCronTrigger('H 0 * * *')

pipeline {
    agent any

    environment {
        PYTHON_ENV = "venv"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Set Up Python Environment') {
            steps {
                script {
                    if (!fileExists("${PYTHON_ENV}")) {
                        sh 'python3 -m venv venv'
                    }
                    sh '. venv/bin/activate'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '. venv/bin/activate && pip install --upgrade pip'
                sh '. venv/bin/activate && pip install -r app/requirements.txt'
            }
        }

        stage('Run Unit Tests') {
            steps {
                sh '. venv/bin/activate && pytest app/test_app.py --junitxml=results.xml'
            }
            post {
                always {
                    junit 'results.xml'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                sh '. venv/bin/activate && coverage run -m pytest app/test_app.py'
                sh '. venv/bin/activate && coverage report'
                sh '. venv/bin/activate && coverage xml'
            }
            post {
                always {
                    publishCoverage adapters: [coberturaAdapter('coverage.xml')]
                }
            }
        }

        stage('Linting') {
            steps {
                sh '. venv/bin/activate && flake8 app/'
                sh '. venv/bin/activate && pylint app/'
                sh '. venv/bin/activate && autopep8 --in-place --aggressive --aggressive app/*.py'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
