deployment:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  sudoku:
    env:
      name: SudokuApp
    image:
      repository: ghcr.io/tarator47/sudoku
      tag: 2025-Q1
    resources:
      limits:
        cpu: 500m
        ephemeral-storage: 100Mi
        memory: 100Mi
      requests:
        cpu: 500m
        ephemeral-storage: 100Mi
        memory: 100Mi
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 7650
    protocol: TCP
    targetPort: 7650
  type: ClusterIP
