@Library('Tarator@main') _
import jenkins.model.Jenkins
import com.tarator.gui.PipelineNames
import com.tarator.jobs.Agent
import com.tarator.gui.JobParameters



pipeline {
    agent {
        kubernetes {
            cloud Agent.K8S_TARATOR
            yaml Agent.getKubernetesAgentYaml()
        }
    }

    parameters {
        booleanParam(name: 'JUST_UPDATE_JOB_CONFIG', defaultValue: false, description:"${JobParameters.PARAM_OPTIONAL} Just Update the configuration of this job - exit on Configuration step")
        booleanParam(name: 'BUILD_GAMES', defaultValue: true, description: 'Build all MES projects (CPG, DevOps, EiHub, Parrot, PharmaSuite, ProductionCentre)')
        booleanParam(name: 'BUILD_SUDOKU', defaultValue: false, description: 'Build administration folder')
    }

    stages {
        stage('Build Projects') {
            when {
                expression { params.JUST_UPDATE_JOB_CONFIG != true && currentBuild.result != 'FAILURE' && currentBuild.result != 'ABORTED' }
            }
            steps {
                script {
                    if (params.BUILD_SUDOKU || params.BUILD_GAMES) {
                        jobDsl targets: 'JobDSL/Sudoku/sudoku_folder_job.groovy', additionalClasspath: 'src/'
                        jobDsl targets: 'JobDSL/Sudoku/sudoku_job.groovy', additionalClasspath: 'src/'
                    }
                }
            }
        }
    }

}
