name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: run linting
        uses: super-linter/super-linter/slim@v5 
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          DISABLE_ERRORS: true 

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: SonarCloud Scan
        run: |
          sonar-scanner \
            -Dsonar.organization="your-organization" \
            -Dsonar.projectKey="your-project-key" \
            -Dsonar.sources="." \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

  snyk:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Snyk Scan
        uses: snyk/actions@v0.6.2
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [Linting, sonarcloud, snyk]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build
        run: |
          # Replace with actual build command
          echo "Building project..."

  trivy:
    name: Trivy Security Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Trivy Scan
        run: |
          docker run --rm -v $(pwd):/project aquasec/trivy fs /project

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Tests
        run: |
          # Replace with actual test command
          echo "Running tests..."

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: [tests, trivy]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy
        run: |
          # Replace with actual deploy command
          echo "Deploying application..."
