name: Minikube Kubernetes Workflow
on:
  push:
    branches:
      - tarator
jobs:
  minikube-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Create Namespace
        run: |
          kubectl create namespace sudoku-app

      - name: Create Secret
        run: |
          kubectl create secret docker-registry -n sudoku-app regcred --docker-username ${{ secrets.DOCKER_USERNAME }} --docker-password ${{ secrets.DOCKER_PASSWORD }} --docker-server gcr.io

      - name: Apply Deployment
        run: |
          kubectl apply -f ./kubernetes/deployment.yaml --namespace=sudoku-app

      - name: Wait for Deployment
        run: |
          kubectl rollout status deployment/sudoku-app-deployment -n sudoku-app --timeout=180s

      - name: Create test namespace
        run: |
          kubectl create namespace test-namespace

      - name: Create service ServiceAccount
        run: |
          kubectl apply -f ./kubernetes/role.yaml

      - name: Run a test pod to check result of home page
        run: |
          kubectl run temp-pod --image=ubuntu --namespace=test-namespace --restart=Never -- sh -c "apt update && apt install -y curl && curl http://sudoku-app-service.sudoku-app.svc.cluster.local:7650"
          kubectl wait --for=condition=ready pod/temp-pod -n test-namespace --timeout=120s
          kubectl logs temp-pod -n test-namespace

