name: Full Minikube and Helm Setup

on:
  workflow_dispatch:

jobs:
  verify-and-install:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Minikube
        run: minikube version || exit 1
        shell: pwsh

      - name: Check kubectl
        run: kubectl version --client || exit 1
        shell: pwsh

      - name: Check Helm
        run: C:\Users\atisw\scoop\shims\helm.exe version || exit 1
        shell: pwsh

      - name: Start Minikube
        run: minikube start --cpus 4 --memory 6144
        shell: pwsh

      - name: Enable Minikube Ingress
        run: minikube addons enable ingress
        shell: pwsh

      - name: Add Helm Repositories
        run: |
          helm repo add jenkins https://charts.jenkins.io
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
        shell: pwsh

      - name: Install Jenkins Helm Chart
        run: C:\Users\atisw\scoop\shims\helm.exe install jenkins jenkins/jenkins -f ./helm/values/jenkins/values.yaml
        shell: pwsh

      # The following steps are commented out, uncomment them if you wish to use them
      # - name: Install Grafana Helm Chart
      #   run: helm install grafana grafana/grafana -f ./helm/values/grafana/values.yaml
      #   shell: pwsh

      # - name: Install Prometheus Helm Chart
      #   run: helm install prometheus prometheus-community/prometheus -f ./helm/values/prometheus/values.yaml
      #   shell: pwsh
