name: CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build And Deploy Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/tarator47/sudoku-app:latest ./app
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push Docker Image
        run: |
          docker push ghcr.io/tarator47/sudoku-app:latest
